package com.company;
import java.util.*;
public class exceptiondemo {
    class myexception extends Exception{

    }



    public static void main(String args[]){
//         String s=null;
//         System.out.println(s.length());
//        System.out.println(4/0);
//        System.out.println("main");
//     int a=6000;
//     int b=0;
////     int c = a/b;
////        System.out.println("The answer is"+" "+c);
//     try{
//         int c = a/b;
//         System.out.println("The answer is"+" "+c);
//     }
//     catch(Exception e){
//         System.out.println("we failed to divide.reason:"+" "+e);
//
//     }
//        System.out.println("end of the program ");
//     int marks[]=new int[3];
//     marks[0]=7;
//     marks[1]=56;
//     marks[2]=6;
//     Scanner sc=new Scanner(System.in);
//        System.out.println("Enter the array index");
//        int ind=sc.nextInt();
//
//        System.out.println("Enter the number you want to divide the value with");
//        int number =sc.nextInt();
//        try{
//            System.out.println("The valur at array index entered is:"+  marks[ind]);
//            System.out.println("the valur of array-value/number is:"+  marks[ind]/number);
//
//        }
//
//        catch(ArithmeticException e){
//            System.out.println("ArithmeticException occured!"+" "+e);
//        }
//        catch(ArrayIndexOutOfBoundsException e){
//            System.out.println("ArrayIndexOutOfBoundsException occured!"+" "+e);
//        }
//        catch(Exception e){
//            System.out.println("Some other exception occured!"+" "+e);
//        }
        //exception class



    }

}
